# Generated by Django 2.0 on 2018-01-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('expression', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('concept', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='spending',
            name='tags',
            field=models.ManyToManyField(blank=True, to='gastos.Tag'),
        ),
        migrations.AddField(
            model_name='autotag',
            name='tags',
            field=models.ManyToManyField(to='gastos.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='spending',
            unique_together={('concept', 'amount', 'date')},
        ),
    ]
